return {

    blue = {
        name = "blue",
        weight = 5
    },

    yellow = {
        name = "blue",
        weight = 5
    },

    red = {
        name = "red",
        weight = 5,
    },

    green = {
        name = "green",
        weight = 4
    },

    purple = {
        name = "purple",
        weight = 4
    },

    pink = {
        name = "pink",
        weight = 2
    },

    magenta = {
        name = "magenta",
        weight = 1
    }

}