name = "alicesaidhi/skilift"
version = "0.3.1"
description = "Lockless DataStore library"
authors = ["alicesaidhi"]
repository = "https://github.com/alicesaidhi/skilift"
license = "MIT"
includes = [
    "src/**",
    "LICENSE",
    "README.md",
    "pesde.toml"
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
